### ISSUE TITLE
'password' column saves as empty string in rails 3

### ISSUE THREAD

**Issue by nunocaldeira** [solymosi/salt-and-pepper#1] opened 2011-05-15 17:01 UTC
The User model has
hash_column :password

When saving a new User, setting the password column seems to work ok, and I am able to see its hashed password. 

But when querying the DB again (such as User.find_by_login('same_user')) the password field its blank

I am using rails 3.0.3

**Comment by solymosi** [comment] 2011-05-15 17:11
By default an empty string is returned when printing the hashed password (= calling password.to_s). This prevents the hash from being displayed in form fields.
You should be able to verify against it, however:
u.password == "something"
=> true
And inspect it in the console:
User.find_by_login('same_user').password.inspect
=> 4e5ab8b39f....

Please report back if this does not work for you and the password is _really_ empty (not just pretends to be blank). Because then it's a bug.

**Comment by nunocaldeira** [comment] 2011-05-15 17:13
Thank you for your quick answer :)
The password column in the database it's blank :(

**Comment by solymosi** [comment] 2011-05-15 17:27
I just ran the tests on Rails 3.0.3 and it completed without failures.
Could you post the code of your user model? Maybe that could shed some light on the problem.

**Comment by nunocaldeira** [comment] 2011-05-15 17:30
my user model: 

class AppUser < ActiveRecord::Base
  hash_column :password
end

(It's not called "User" as I posted before)

**Comment by nunocaldeira** [comment] 2011-05-15 17:43
I think this is the best way I can explain what is happening.

rails console:

a = AppUser.find 2
 => # AppUser id: 2, login: "nuno", password: "", name: nil, email: nil, crypted_password: nil, password_salt: nil, persistence_token: nil, login_count: 0, failed_login_count: 0, last_request_at: nil, current_login_at: nil, last_login_at: nil, current_login_ip: nil, last_login_ip: nil
ruby-1.9.2-p0 > a.password = "nuno"
 => "nuno" 
ruby-1.9.2-p0 > a.save
 => true 
ruby-1.9.2-p0 > a
 => # AppUser id: 2, login: "nuno", password: "b9f6861baf9c51461fb663e683c45c848ab46df3c24a2d796d7a4537be84cd38aa3f2682a16ddf4948d527c3b66ad4099b110817c204357a1ad15b97ede969a8", name: nil, email: nil, crypted_password: nil, password_salt: nil, persistence_token: nil, login_count: 0, failed_login_count: 0, last_request_at: nil, current_login_at: nil, last_login_at: nil, current_login_ip: nil, last_login_ip: nil
ruby-1.9.2-p0 > a = AppUser.find 2
 => # AppUser id: 2, login: "nuno", password: "", name: nil, email: nil, crypted_password: nil, password_salt: nil, persistence_token: nil, login_count: 0, failed_login_count: 0, last_request_at: nil, current_login_at: nil, last_login_at: nil, current_login_ip: nil, last_login_ip: nil
ruby-1.9.2-p0 > a.password == ""
 => true

(I chopped some chars so it gets printed)

**Comment by solymosi** [comment] 2011-05-15 17:47
Thanks, I was able to reproduce the problem on Rails 3.0.3.
Let me figure out what's causing this...

**Comment by solymosi** [comment] 2011-05-15 19:05
Okay, I solved it. The issue was the following:
When saving the object, salt and pepper converts the password to a HashedString object. HashedString#to_s returns a blank string (so it's not ugly when displayed in a form) and HashedString#to_yaml returns the actual hashed value (this is used when saving to the database). The problem was that from v3.0.1 to v3.0.4 Rails calls to_s and not to_yaml when saving a value of unknown type (like HashedString).
Possible solution 1: make to_s return the hashed value instead of ""
Possible solution 2: require at least Rails 3.0.4
The first needs workarounds when a hashed attribute is displayed in forms, so I went with the second solution.
Please upgrade Rails and the problem will be fixed.

**Comment by nunocaldeira** [comment] 2011-05-15 19:31
Thanks,
Updated rails and everything is working now :)

**Closed as completed** 2014-11-17 22:21 UTC
